### ISSUE TITLE
Calendar does not work

### ISSUE THREAD

**Issue by rafboogie** [adareau/pyfit-gui#1]
Selecting root folder for calendar selection of pictures does not work.

**Comment by adareau** [comment]
Please specify the environment in which the bug is occurring :-)

**Comment by adareau** [comment]
**QUICKFIX : commit 87db839**

This bug is specific to our folder tree configuration : we use something that looks like "2015/Oct2015/29Oct2015". In my installation of windows 7, 'Oct' is obtained with the datetime strftime function (https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior) with the directive "%b" (Month as locale’s abbreviated name). On linux (Ubuntu 14.04) this was returning 'oct.'

My - ugly - fix is the following : checking the month format on january, and if it does not return "Jan" then we remove the dot at the end (if there is one) and make the first letter uppercase. One would have to adapt this to its own folder tree.

The code is the following (in start.py):

``` python
## QUICKFIX : fixing the calendar issue for linux
# our folder tree looks like "root/2015/Oct2015/01Oct2015/"
# with windows we get the "Oct" using the string formatting "%b" (Locale’s abbreviated month name)
# on linux (tested on Ubuntu 14.04) it returns 'oct.' => wee need uppercase + remove the dot
# [temporary (?) fix] => test if january returns "Jan", otherwise fix the month

test_month = datetime.date(2000,1,1).strftime('%b')
if test_month != 'Jan':
    bad_month = date.strftime('%b')
    good_month = bad_month[:]

    if good_month[-1]=='.':
        good_month = good_month[:-1]
    if good_month[0].islower():
        good_month = good_month[0].upper()+good_month[1:]

    day_folder = day_folder.replace(bad_month,good_month)
    month_folder = month_folder.replace(bad_month,good_month)
### END OF QUICKFIX
## TODO : improve ?
```
